Repository ASSU-org/ASSU_FE_app, pull requests merged in 2025-09, with the labels that each got.

#69 [FEAT/#68] 로그인 연동 및 토큰 매니저
  app/build.gradle.kts
  app/src/main/java/com/example/assu_fe_app/MyApplication.java
  app/src/main/java/com/example/assu_fe_app/data/DevBearerInterceptor.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/CommonLoginRequestDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/CommonLoginResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/LoginRequestDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/LoginResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/manager/TokenManager.kt
  app/src/main/java/com/example/assu_fe_app/data/repository/auth/AuthRepository.kt
  app/src/main/java/com/example/assu_fe_app/data/repository/deviceToken/DeviceTokenRepository.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/deviceToken/DeviceTokenRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/service/auth/AuthService.kt
  app/src/main/java/com/example/assu_fe_app/data/service/deviceToken/DeviceTokenService.kt
  app/src/main/java/com/example/assu_fe_app/di/RepoModule.kt
  app/src/main/java/com/example/assu_fe_app/di/ServiceModule.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/auth/LoginModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/common/RetrofitResult.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/auth/CommonLoginUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/auth/LogoutUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/auth/StudentLoginUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/deviceToken/UnregisterDeviceTokenUseCase.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/mypage/AdminMypageFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LmsLoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LoginViewModel.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/home/PartnerHomeFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/mypage/PartnerMypageFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/mypage/UserMypageFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/deviceToken/DeviceTokenViewModel.kt
  app/src/main/java/com/example/assu_fe_app/util/apiHandler.kt
  app/src/main/res/layout/activity_lms_login.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feature⭐️, refactor⛏️

#75 Feat/#53 chatting api connect
  app/build.gradle.kts
  app/src/main/java/com/example/assu_fe_app/data/dto/BaseResponse.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/ChattingMessageItem.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/ChattingRoomListItem.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/WsMessageDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/response/GetChatHistoryResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/response/GetChattingRoomListResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/response/LeaveChattingRoomResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/chatting/response/ReadChattingResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/local/TokenProvider.kt
  app/src/main/java/com/example/assu_fe_app/data/local/TokenProviderImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/remote/AuthInterceptor.kt
  app/src/main/java/com/example/assu_fe_app/data/repository/chatting/ChattingRepository.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/chatting/ChattingRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/service/chatting/ChattingService.kt
  app/src/main/java/com/example/assu_fe_app/data/socket/ChatSocketClient.kt
  app/src/main/java/com/example/assu_fe_app/di/RepoModule.kt
  app/src/main/java/com/example/assu_fe_app/di/SocketModule.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/chatting/GetChatHistoryModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/chatting/GetChattingRoomListModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/chatting/LeaveChattingRoomModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/chatting/ReadChattingModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/chatting/GetChatHistoryUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/chatting/GetChattingRoomListUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/chatting/LeaveChattingRoomUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/chatting/ReadChattingUseCase.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/AdminMainActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/home/AdminHomeFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/chatting/ChattingActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/chatting/ChattingListFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/chatting/ChattingRoomListFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/chatting/adapter/ChattingChatListAdapter.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/chatting/adapter/ChattingMessageAdapter.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/chatting/adapter/ChattingRoomListAdapter.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/location/LocationFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/home/PartnerHomeFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/chatting/ChattingViewModel.kt
  app/src/main/res/layout/activity_chatting.xml
  app/src/main/res/layout/fragment_chatting_list.xml
  app/src/main/res/layout/fragment_partner_home.xml
  app/src/main/res/layout/item_chat_mine.xml
  app/src/main/res/layout/item_chat_other.xml
  app/src/main/res/navigation/admin_nav_graph.xml
  app/src/main/res/navigation/partner_nav_graph.xml
  app/src/main/res/xml/network_security_config.xml
  settings.gradle.kts
Labels: feature⭐️

#84 [FEAT/#70] phone verify and withdraw api
  app/src/main/java/com/example/assu_fe_app/MyApplication.java
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/CommonLoginResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/LoginResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/PhoneVerificationDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/UserBasicInfoDto.kt
  app/src/main/java/com/example/assu_fe_app/data/manager/TokenManager.kt
  app/src/main/java/com/example/assu_fe_app/data/repository/auth/AuthRepository.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/service/auth/AuthService.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/auth/LoginModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/auth/UserBasicInfo.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/auth/WithdrawUseCase.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/mypage/AdminMypageFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LmsLoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LoginViewModel.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/mypage/MypageAccountFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/mypage/SecessionDialogFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpVerifyFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/mypage/PartnerMypageFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/mypage/UserMypageFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/LoginViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/SignUpVerifyViewModel.kt
  app/src/main/res/layout/dialog_secession.xml
Labels: feature⭐️

#115 [REFACTOR/#113] QA 반영
  app/src/main/java/com/example/assu_fe_app/data/dto/ProposalItem.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/admin/RandomPartnerResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/location/LocationAdminPartnerSearchResultItem.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/location/response/AdminMapResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/location/response/PartnerMapResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/location/response/StoreMapResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/partner/RandomAdminResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/partnership/response/PartnershipOptionResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/admin/AdminHomeRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/location/LocationRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/partner/PartnerHomeRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/di/SocketModule.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/admin/RecommendedPartnerModel.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/location/AdminOnMap.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/location/PartnerOnMap.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/location/StoreOnMap.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/partner/RecommendedAdminModel.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/home/AdminHomeFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/home/ServicePassivityProposalWritingFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/home/adapter/ProposalItemMappers.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/home/adapter/ServicePassiveProposalAdapter.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/mypage/AdminDeleteContractDialogFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/mypage/AdminMypagePendingPartnershipDialogFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/location/LocationFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/location/LocationItemFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/location/LocationSearchSuccessFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/location/adapter/AdminParterLocationAdapter.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/mypage/CustomerServiceDialogFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/mypage/InquiryDetailDialogFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/mypage/SecessionDialogFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/home/PartnerHomeFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/location/UserLocationFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/inquiry/InquiryViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/map/MapBridgeViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/partnership/AdminPendingPartnershipViewModel.kt
  app/src/main/res/drawable/btn_recommend_inquiry.xml
  app/src/main/res/layout/dialog_admin_delete_contract.xml
  app/src/main/res/layout/dialog_secession.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/layout/fragment_admin_mypage_pending_partnership.xml
  app/src/main/res/layout/fragment_partner_home.xml
  app/src/main/res/layout/fragment_user_customer_service.xml
  app/src/main/res/layout/fragment_user_inquiry_detail.xml
Labels: refactor⛏️
