Repository ASSU-org/ASSU_FE_app, pull requests merged in 2025-10, with the labels that each got.

#118 [REFACTOR/#112] 검색화면 수정
  app/src/main/java/com/example/assu_fe_app/presentation/common/location/LocationSearchActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/search/LocationInfoSearchFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/location/UserLocationSearchActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/location/UserLocationSearchRankFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/map/UserLocationSearchViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/search/LocationInfoSearchViewModel.kt
  app/src/main/res/layout/activity_location_search.xml
  app/src/main/res/layout/activity_user_location_search.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_location_info_search.xml
Labels: fix🐞

#120 [REFACTOR/#119] 회원가입 및 로그인 4차 QA 반영
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/assu_fe_app/MyApplication.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/RefreshResponseDto.kt
  app/src/main/java/com/example/assu_fe_app/data/remote/AuthInterceptor.kt
  app/src/main/java/com/example/assu_fe_app/data/remote/TokenRefreshInterceptor.kt
  app/src/main/java/com/example/assu_fe_app/data/repository/TokenRefreshRepository.kt
  app/src/main/java/com/example/assu_fe_app/di/ServiceModule.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/auth/CommonLoginUseCase.kt
  app/src/main/java/com/example/assu_fe_app/domain/usecase/auth/StudentLoginUseCase.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/signup/AdminSignUpSealFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LmsLoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/mypage/MypageAccountFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpAccountFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpCompleteFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpVerifyFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/signup/PartnerSignUpLicenseFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/signup/UserSignUpStudentCheckFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/signup/UserSignUpStudentFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/LoginErrorMessageMapper.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/LoginViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/SignUpVerifyViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/SignUpViewModel.kt
  app/src/main/java/com/example/assu_fe_app/util/RetrofitResult.kt
  app/src/main/java/com/example/assu_fe_app/util/ToastUtil.kt
  app/src/main/java/com/example/assu_fe_app/util/apiHandler.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/toast_background.xml
  app/src/main/res/layout/dropdown_admin_part.xml
  app/src/main/res/layout/fragment_admin_sign_up_info.xml
  app/src/main/res/layout/fragment_mypage_account.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: refactor⛏️

#126 [FIX/#119] 회원가입 및 로그인 4차 QA
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/AdminSignUpRequestDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/PartnerSignUpRequestDto.kt
  app/src/main/java/com/example/assu_fe_app/data/dto/auth/StudentTokenSignUpRequestDto.kt
  app/src/main/java/com/example/assu_fe_app/data/repositoryImpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/example/assu_fe_app/domain/model/auth/SignUpData.kt
  app/src/main/java/com/example/assu_fe_app/presentation/admin/signup/AdminSignUpSealFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpCompleteFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpVerifyFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/partner/signup/PartnerSignUpLicenseFragment.kt
  app/src/main/java/com/example/assu_fe_app/presentation/user/signup/UserSignUpStudentCheckFragment.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/SignUpVerifyViewModel.kt
  app/src/main/java/com/example/assu_fe_app/ui/auth/SignUpViewModel.kt
  app/src/main/res/layout/fragment_sign_up_complete.xml
  app/src/main/res/layout/fragment_sign_up_verify.xml
Labels: fix🐞

#127 [REFACTOR/#112] 가격확인 화면 수정
  app/src/main/res/layout/fragment_user_price_confirm.xml
Labels: fix🐞, refactor⛏️

#131 [FIX/#130] 회원가입 후 타입별 진입화면으로 이동하도록 수정
  app/src/main/java/com/example/assu_fe_app/data/remote/AuthInterceptor.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/login/LoginActivity.kt
  app/src/main/java/com/example/assu_fe_app/presentation/common/signup/SignUpCompleteFragment.kt
Labels: fix🐞
